// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xawgn.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XAwgn_CfgInitialize(XAwgn *InstancePtr, XAwgn_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_axil_BaseAddress = ConfigPtr->Control_axil_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XAwgn_Start(XAwgn *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAwgn_ReadReg(InstancePtr->Control_axil_BaseAddress, XAWGN_CONTROL_AXIL_ADDR_AP_CTRL) & 0x80;
    XAwgn_WriteReg(InstancePtr->Control_axil_BaseAddress, XAWGN_CONTROL_AXIL_ADDR_AP_CTRL, Data | 0x01);
}

u32 XAwgn_IsDone(XAwgn *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAwgn_ReadReg(InstancePtr->Control_axil_BaseAddress, XAWGN_CONTROL_AXIL_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XAwgn_IsIdle(XAwgn *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAwgn_ReadReg(InstancePtr->Control_axil_BaseAddress, XAWGN_CONTROL_AXIL_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XAwgn_IsReady(XAwgn *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAwgn_ReadReg(InstancePtr->Control_axil_BaseAddress, XAWGN_CONTROL_AXIL_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XAwgn_EnableAutoRestart(XAwgn *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAwgn_WriteReg(InstancePtr->Control_axil_BaseAddress, XAWGN_CONTROL_AXIL_ADDR_AP_CTRL, 0x80);
}

void XAwgn_DisableAutoRestart(XAwgn *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAwgn_WriteReg(InstancePtr->Control_axil_BaseAddress, XAWGN_CONTROL_AXIL_ADDR_AP_CTRL, 0);
}

void XAwgn_Set_stdd(XAwgn *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAwgn_WriteReg(InstancePtr->Control_axil_BaseAddress, XAWGN_CONTROL_AXIL_ADDR_STDD_DATA, Data);
}

u32 XAwgn_Get_stdd(XAwgn *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAwgn_ReadReg(InstancePtr->Control_axil_BaseAddress, XAWGN_CONTROL_AXIL_ADDR_STDD_DATA);
    return Data;
}

void XAwgn_Set_enable(XAwgn *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAwgn_WriteReg(InstancePtr->Control_axil_BaseAddress, XAWGN_CONTROL_AXIL_ADDR_ENABLE_DATA, Data);
}

u32 XAwgn_Get_enable(XAwgn *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XAwgn_ReadReg(InstancePtr->Control_axil_BaseAddress, XAWGN_CONTROL_AXIL_ADDR_ENABLE_DATA);
    return Data;
}

void XAwgn_InterruptGlobalEnable(XAwgn *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAwgn_WriteReg(InstancePtr->Control_axil_BaseAddress, XAWGN_CONTROL_AXIL_ADDR_GIE, 1);
}

void XAwgn_InterruptGlobalDisable(XAwgn *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAwgn_WriteReg(InstancePtr->Control_axil_BaseAddress, XAWGN_CONTROL_AXIL_ADDR_GIE, 0);
}

void XAwgn_InterruptEnable(XAwgn *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XAwgn_ReadReg(InstancePtr->Control_axil_BaseAddress, XAWGN_CONTROL_AXIL_ADDR_IER);
    XAwgn_WriteReg(InstancePtr->Control_axil_BaseAddress, XAWGN_CONTROL_AXIL_ADDR_IER, Register | Mask);
}

void XAwgn_InterruptDisable(XAwgn *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XAwgn_ReadReg(InstancePtr->Control_axil_BaseAddress, XAWGN_CONTROL_AXIL_ADDR_IER);
    XAwgn_WriteReg(InstancePtr->Control_axil_BaseAddress, XAWGN_CONTROL_AXIL_ADDR_IER, Register & (~Mask));
}

void XAwgn_InterruptClear(XAwgn *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XAwgn_WriteReg(InstancePtr->Control_axil_BaseAddress, XAWGN_CONTROL_AXIL_ADDR_ISR, Mask);
}

u32 XAwgn_InterruptGetEnabled(XAwgn *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XAwgn_ReadReg(InstancePtr->Control_axil_BaseAddress, XAWGN_CONTROL_AXIL_ADDR_IER);
}

u32 XAwgn_InterruptGetStatus(XAwgn *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XAwgn_ReadReg(InstancePtr->Control_axil_BaseAddress, XAWGN_CONTROL_AXIL_ADDR_ISR);
}

