// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xpwm_prepare.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XPwm_prepare_CfgInitialize(XPwm_prepare *InstancePtr, XPwm_prepare_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_axil_BaseAddress = ConfigPtr->Control_axil_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XPwm_prepare_Start(XPwm_prepare *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPwm_prepare_ReadReg(InstancePtr->Control_axil_BaseAddress, XPWM_PREPARE_CONTROL_AXIL_ADDR_AP_CTRL) & 0x80;
    XPwm_prepare_WriteReg(InstancePtr->Control_axil_BaseAddress, XPWM_PREPARE_CONTROL_AXIL_ADDR_AP_CTRL, Data | 0x01);
}

u32 XPwm_prepare_IsDone(XPwm_prepare *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPwm_prepare_ReadReg(InstancePtr->Control_axil_BaseAddress, XPWM_PREPARE_CONTROL_AXIL_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XPwm_prepare_IsIdle(XPwm_prepare *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPwm_prepare_ReadReg(InstancePtr->Control_axil_BaseAddress, XPWM_PREPARE_CONTROL_AXIL_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XPwm_prepare_IsReady(XPwm_prepare *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPwm_prepare_ReadReg(InstancePtr->Control_axil_BaseAddress, XPWM_PREPARE_CONTROL_AXIL_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XPwm_prepare_EnableAutoRestart(XPwm_prepare *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPwm_prepare_WriteReg(InstancePtr->Control_axil_BaseAddress, XPWM_PREPARE_CONTROL_AXIL_ADDR_AP_CTRL, 0x80);
}

void XPwm_prepare_DisableAutoRestart(XPwm_prepare *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPwm_prepare_WriteReg(InstancePtr->Control_axil_BaseAddress, XPWM_PREPARE_CONTROL_AXIL_ADDR_AP_CTRL, 0);
}

void XPwm_prepare_Set_shift_val(XPwm_prepare *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPwm_prepare_WriteReg(InstancePtr->Control_axil_BaseAddress, XPWM_PREPARE_CONTROL_AXIL_ADDR_SHIFT_VAL_DATA, Data);
}

u32 XPwm_prepare_Get_shift_val(XPwm_prepare *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPwm_prepare_ReadReg(InstancePtr->Control_axil_BaseAddress, XPWM_PREPARE_CONTROL_AXIL_ADDR_SHIFT_VAL_DATA);
    return Data;
}

void XPwm_prepare_Set_sum_val(XPwm_prepare *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPwm_prepare_WriteReg(InstancePtr->Control_axil_BaseAddress, XPWM_PREPARE_CONTROL_AXIL_ADDR_SUM_VAL_DATA, Data);
}

u32 XPwm_prepare_Get_sum_val(XPwm_prepare *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPwm_prepare_ReadReg(InstancePtr->Control_axil_BaseAddress, XPWM_PREPARE_CONTROL_AXIL_ADDR_SUM_VAL_DATA);
    return Data;
}

void XPwm_prepare_Set_enable_flag(XPwm_prepare *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPwm_prepare_WriteReg(InstancePtr->Control_axil_BaseAddress, XPWM_PREPARE_CONTROL_AXIL_ADDR_ENABLE_FLAG_DATA, Data);
}

u32 XPwm_prepare_Get_enable_flag(XPwm_prepare *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XPwm_prepare_ReadReg(InstancePtr->Control_axil_BaseAddress, XPWM_PREPARE_CONTROL_AXIL_ADDR_ENABLE_FLAG_DATA);
    return Data;
}

void XPwm_prepare_InterruptGlobalEnable(XPwm_prepare *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPwm_prepare_WriteReg(InstancePtr->Control_axil_BaseAddress, XPWM_PREPARE_CONTROL_AXIL_ADDR_GIE, 1);
}

void XPwm_prepare_InterruptGlobalDisable(XPwm_prepare *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPwm_prepare_WriteReg(InstancePtr->Control_axil_BaseAddress, XPWM_PREPARE_CONTROL_AXIL_ADDR_GIE, 0);
}

void XPwm_prepare_InterruptEnable(XPwm_prepare *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XPwm_prepare_ReadReg(InstancePtr->Control_axil_BaseAddress, XPWM_PREPARE_CONTROL_AXIL_ADDR_IER);
    XPwm_prepare_WriteReg(InstancePtr->Control_axil_BaseAddress, XPWM_PREPARE_CONTROL_AXIL_ADDR_IER, Register | Mask);
}

void XPwm_prepare_InterruptDisable(XPwm_prepare *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XPwm_prepare_ReadReg(InstancePtr->Control_axil_BaseAddress, XPWM_PREPARE_CONTROL_AXIL_ADDR_IER);
    XPwm_prepare_WriteReg(InstancePtr->Control_axil_BaseAddress, XPWM_PREPARE_CONTROL_AXIL_ADDR_IER, Register & (~Mask));
}

void XPwm_prepare_InterruptClear(XPwm_prepare *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XPwm_prepare_WriteReg(InstancePtr->Control_axil_BaseAddress, XPWM_PREPARE_CONTROL_AXIL_ADDR_ISR, Mask);
}

u32 XPwm_prepare_InterruptGetEnabled(XPwm_prepare *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XPwm_prepare_ReadReg(InstancePtr->Control_axil_BaseAddress, XPWM_PREPARE_CONTROL_AXIL_ADDR_IER);
}

u32 XPwm_prepare_InterruptGetStatus(XPwm_prepare *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XPwm_prepare_ReadReg(InstancePtr->Control_axil_BaseAddress, XPWM_PREPARE_CONTROL_AXIL_ADDR_ISR);
}

