// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XAWGN_H
#define XAWGN_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xawgn_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Control_axil_BaseAddress;
} XAwgn_Config;
#endif

typedef struct {
    u32 Control_axil_BaseAddress;
    u32 IsReady;
} XAwgn;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XAwgn_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XAwgn_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XAwgn_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XAwgn_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XAwgn_Initialize(XAwgn *InstancePtr, u16 DeviceId);
XAwgn_Config* XAwgn_LookupConfig(u16 DeviceId);
int XAwgn_CfgInitialize(XAwgn *InstancePtr, XAwgn_Config *ConfigPtr);
#else
int XAwgn_Initialize(XAwgn *InstancePtr, const char* InstanceName);
int XAwgn_Release(XAwgn *InstancePtr);
#endif

void XAwgn_Start(XAwgn *InstancePtr);
u32 XAwgn_IsDone(XAwgn *InstancePtr);
u32 XAwgn_IsIdle(XAwgn *InstancePtr);
u32 XAwgn_IsReady(XAwgn *InstancePtr);
void XAwgn_EnableAutoRestart(XAwgn *InstancePtr);
void XAwgn_DisableAutoRestart(XAwgn *InstancePtr);

void XAwgn_Set_stdd(XAwgn *InstancePtr, u32 Data);
u32 XAwgn_Get_stdd(XAwgn *InstancePtr);
void XAwgn_Set_enable(XAwgn *InstancePtr, u32 Data);
u32 XAwgn_Get_enable(XAwgn *InstancePtr);

void XAwgn_InterruptGlobalEnable(XAwgn *InstancePtr);
void XAwgn_InterruptGlobalDisable(XAwgn *InstancePtr);
void XAwgn_InterruptEnable(XAwgn *InstancePtr, u32 Mask);
void XAwgn_InterruptDisable(XAwgn *InstancePtr, u32 Mask);
void XAwgn_InterruptClear(XAwgn *InstancePtr, u32 Mask);
u32 XAwgn_InterruptGetEnabled(XAwgn *InstancePtr);
u32 XAwgn_InterruptGetStatus(XAwgn *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
