// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xawgn.h"

extern XAwgn_Config XAwgn_ConfigTable[];

XAwgn_Config *XAwgn_LookupConfig(u16 DeviceId) {
	XAwgn_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XAWGN_NUM_INSTANCES; Index++) {
		if (XAwgn_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XAwgn_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XAwgn_Initialize(XAwgn *InstancePtr, u16 DeviceId) {
	XAwgn_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XAwgn_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XAwgn_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

