// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xpwm_prepare.h"

extern XPwm_prepare_Config XPwm_prepare_ConfigTable[];

XPwm_prepare_Config *XPwm_prepare_LookupConfig(u16 DeviceId) {
	XPwm_prepare_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XPWM_PREPARE_NUM_INSTANCES; Index++) {
		if (XPwm_prepare_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XPwm_prepare_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XPwm_prepare_Initialize(XPwm_prepare *InstancePtr, u16 DeviceId) {
	XPwm_prepare_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XPwm_prepare_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XPwm_prepare_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

