#pragma line 1 "awgn/solution1/awgn.c" ::: -10
#pragma line 1 "awgn/solution1/awgn.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 149 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 0
#pragma line 283 "/opt/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 53
#pragma line 421 "/opt/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 180
#pragma line 6 "<command line>" 2 ::: 182
#pragma line 1 "<built-in>" 2 ::: 183
#pragma line 1 "awgn/solution1/awgn.c" 2 ::: 184
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdint.h" 1 3 ::: 185
#pragma line 1 "/usr/include/stdint.h" 1 3 4 ::: 219
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 245
#pragma line 122 "/usr/include/features.h" 3 4 ::: 342
#pragma line 156 "/usr/include/features.h" 3 4 ::: 367
#pragma line 180 "/usr/include/features.h" 3 4 ::: 369
#pragma line 191 "/usr/include/features.h" 3 4 ::: 372
#pragma line 343 "/usr/include/features.h" 3 4 ::: 403
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 407
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 442
#pragma line 346 "/usr/include/features.h" 2 3 4 ::: 449
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 472
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 513
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 519
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 537
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 543
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 547
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 549
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 553
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 563
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 616
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 657
#pragma line 346 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 682
#pragma line 410 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 706
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 707
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 709
#pragma line 411 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 711
#pragma line 368 "/usr/include/features.h" 2 3 4 ::: 712
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 737
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 748
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 753
#pragma line 392 "/usr/include/features.h" 2 3 4 ::: 754
#pragma line 26 "/usr/include/stdint.h" 2 3 4 ::: 755
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wchar.h" 1 3 4 ::: 756
#pragma line 27 "/usr/include/stdint.h" 2 3 4 ::: 788
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 789
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 791
#pragma line 28 "/usr/include/stdint.h" 2 3 4 ::: 793
#pragma line 116 "/usr/include/stdint.h" 3 4 ::: 874
#pragma line 132 "/usr/include/stdint.h" 3 4 ::: 882
#pragma line 152 "/usr/include/stdint.h" 3 4 ::: 887
#pragma line 200 "/usr/include/stdint.h" 3 4 ::: 927
#pragma line 211 "/usr/include/stdint.h" 3 4 ::: 929
#pragma line 223 "/usr/include/stdint.h" 3 4 ::: 931
#pragma line 235 "/usr/include/stdint.h" 3 4 ::: 933
#pragma line 255 "/usr/include/stdint.h" 3 4 ::: 946
#pragma line 270 "/usr/include/stdint.h" 3 4 ::: 952
#pragma line 291 "/usr/include/stdint.h" 3 4 ::: 965
#pragma line 301 "/usr/include/stdint.h" 3 4 ::: 967
#pragma line 34 "/opt/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdint.h" 2 3 ::: 969
#pragma line 2 "awgn/solution1/awgn.c" 2 ::: 970
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdbool.h" 1 3 ::: 971
#pragma line 3 "awgn/solution1/awgn.c" 2 ::: 1001
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 1002
#pragma line 30 "/usr/include/math.h" 3 4 ::: 1024
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 1 3 4 ::: 1027
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/libm-simd-decl-stubs.h" 1 3 4 ::: 1053
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 2 3 4 ::: 1085
#pragma line 32 "/usr/include/math.h" 2 3 4 ::: 1086
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_val.h" 1 3 4 ::: 1091
#pragma line 36 "/usr/include/math.h" 2 3 4 ::: 1116
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_valf.h" 1 3 4 ::: 1118
#pragma line 38 "/usr/include/math.h" 2 3 4 ::: 1143
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_vall.h" 1 3 4 ::: 1144
#pragma line 39 "/usr/include/math.h" 2 3 4 ::: 1163
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/inf.h" 1 3 4 ::: 1167
#pragma line 42 "/usr/include/math.h" 2 3 4 ::: 1191
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/nan.h" 1 3 4 ::: 1195
#pragma line 45 "/usr/include/math.h" 2 3 4 ::: 1220
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 1 3 4 ::: 1225
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 3 4 ::: 1242
#pragma line 41 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 3 4 ::: 1248
#pragma line 49 "/usr/include/math.h" 2 3 4 ::: 1255
#pragma line 83 "/usr/include/math.h" 3 4 ::: 1261
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 1262
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1339
#pragma line 127 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1369
#pragma line 382 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1610
#pragma line 84 "/usr/include/math.h" 2 3 4 ::: 1613
#pragma line 93 "/usr/include/math.h" 3 4 ::: 1614
#pragma line 104 "/usr/include/math.h" 3 4 ::: 1617
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 1618
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1695
#pragma line 127 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1725
#pragma line 382 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1966
#pragma line 105 "/usr/include/math.h" 2 3 4 ::: 1969
#pragma line 139 "/usr/include/math.h" 3 4 ::: 1970
#pragma line 151 "/usr/include/math.h" 3 4 ::: 1973
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 1974
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 2051
#pragma line 127 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 2081
#pragma line 382 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 2322
#pragma line 152 "/usr/include/math.h" 2 3 4 ::: 2325
#pragma line 167 "/usr/include/math.h" 3 4 ::: 2326
#pragma line 248 "/usr/include/math.h" 3 4 ::: 2393
#pragma line 268 "/usr/include/math.h" 3 4 ::: 2395
#pragma line 282 "/usr/include/math.h" 3 4 ::: 2397
#pragma line 304 "/usr/include/math.h" 3 4 ::: 2407
#pragma line 318 "/usr/include/math.h" 3 4 ::: 2409
#pragma line 346 "/usr/include/math.h" 3 4 ::: 2417
#pragma line 411 "/usr/include/math.h" 3 4 ::: 2471
#pragma line 428 "/usr/include/math.h" 3 4 ::: 2473
#pragma line 448 "/usr/include/math.h" 3 4 ::: 2477
#pragma line 470 "/usr/include/math.h" 3 4 ::: 2492
#pragma line 4 "awgn/solution1/awgn.c" 2 ::: 2548
