#pragma line 1 "awgn/solution1/awgn.c" ::: 0
#pragma line 1 "awgn/solution1/awgn.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 149 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 10
#pragma line 283 "/opt/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 63
#pragma line 421 "/opt/Xilinx/Vivado_HLS/2016.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 190
#pragma line 6 "<command line>" 2 ::: 192
#pragma line 1 "<built-in>" 2 ::: 193
#pragma line 1 "awgn/solution1/awgn.c" 2 ::: 194
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdint.h" 1 3 ::: 195
#pragma line 1 "/usr/include/stdint.h" 1 3 4 ::: 229
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 255
#pragma line 122 "/usr/include/features.h" 3 4 ::: 352
#pragma line 156 "/usr/include/features.h" 3 4 ::: 377
#pragma line 180 "/usr/include/features.h" 3 4 ::: 379
#pragma line 191 "/usr/include/features.h" 3 4 ::: 382
#pragma line 343 "/usr/include/features.h" 3 4 ::: 413
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 417
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 452
#pragma line 346 "/usr/include/features.h" 2 3 4 ::: 459
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 482
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 523
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 529
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 547
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 553
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 557
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 559
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 563
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 573
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 626
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 667
#pragma line 346 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 692
#pragma line 410 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 716
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 717
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 719
#pragma line 411 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 721
#pragma line 368 "/usr/include/features.h" 2 3 4 ::: 722
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 747
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 758
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 763
#pragma line 392 "/usr/include/features.h" 2 3 4 ::: 764
#pragma line 26 "/usr/include/stdint.h" 2 3 4 ::: 765
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wchar.h" 1 3 4 ::: 766
#pragma line 27 "/usr/include/stdint.h" 2 3 4 ::: 798
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 799
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 801
#pragma line 28 "/usr/include/stdint.h" 2 3 4 ::: 803
#pragma line 116 "/usr/include/stdint.h" 3 4 ::: 884
#pragma line 132 "/usr/include/stdint.h" 3 4 ::: 892
#pragma line 152 "/usr/include/stdint.h" 3 4 ::: 897
#pragma line 200 "/usr/include/stdint.h" 3 4 ::: 937
#pragma line 211 "/usr/include/stdint.h" 3 4 ::: 939
#pragma line 223 "/usr/include/stdint.h" 3 4 ::: 941
#pragma line 235 "/usr/include/stdint.h" 3 4 ::: 943
#pragma line 255 "/usr/include/stdint.h" 3 4 ::: 956
#pragma line 270 "/usr/include/stdint.h" 3 4 ::: 962
#pragma line 291 "/usr/include/stdint.h" 3 4 ::: 975
#pragma line 301 "/usr/include/stdint.h" 3 4 ::: 977
#pragma line 34 "/opt/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdint.h" 2 3 ::: 979
#pragma line 2 "awgn/solution1/awgn.c" 2 ::: 980
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2016.2/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdbool.h" 1 3 ::: 981
#pragma line 3 "awgn/solution1/awgn.c" 2 ::: 1011
#pragma line 1 "/usr/include/math.h" 1 3 4 ::: 1012
#pragma line 30 "/usr/include/math.h" 3 4 ::: 1034
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 1 3 4 ::: 1037
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/libm-simd-decl-stubs.h" 1 3 4 ::: 1063
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/math-vector.h" 2 3 4 ::: 1095
#pragma line 32 "/usr/include/math.h" 2 3 4 ::: 1096
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_val.h" 1 3 4 ::: 1101
#pragma line 36 "/usr/include/math.h" 2 3 4 ::: 1126
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_valf.h" 1 3 4 ::: 1128
#pragma line 38 "/usr/include/math.h" 2 3 4 ::: 1153
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/huge_vall.h" 1 3 4 ::: 1154
#pragma line 39 "/usr/include/math.h" 2 3 4 ::: 1173
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/inf.h" 1 3 4 ::: 1177
#pragma line 42 "/usr/include/math.h" 2 3 4 ::: 1201
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/nan.h" 1 3 4 ::: 1205
#pragma line 45 "/usr/include/math.h" 2 3 4 ::: 1230
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 1 3 4 ::: 1235
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 3 4 ::: 1252
#pragma line 41 "/usr/include/x86_64-linux-gnu/bits/mathdef.h" 3 4 ::: 1258
#pragma line 49 "/usr/include/math.h" 2 3 4 ::: 1265
#pragma line 83 "/usr/include/math.h" 3 4 ::: 1271
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 1272
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1349
#pragma line 127 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1379
#pragma line 382 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1620
#pragma line 84 "/usr/include/math.h" 2 3 4 ::: 1623
#pragma line 93 "/usr/include/math.h" 3 4 ::: 1624
#pragma line 104 "/usr/include/math.h" 3 4 ::: 1627
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 1628
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1705
#pragma line 127 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1735
#pragma line 382 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 1976
#pragma line 105 "/usr/include/math.h" 2 3 4 ::: 1979
#pragma line 139 "/usr/include/math.h" 3 4 ::: 1980
#pragma line 151 "/usr/include/math.h" 3 4 ::: 1983
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 1 3 4 ::: 1984
#pragma line 87 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 2061
#pragma line 127 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 2091
#pragma line 382 "/usr/include/x86_64-linux-gnu/bits/mathcalls.h" 3 4 ::: 2332
#pragma line 152 "/usr/include/math.h" 2 3 4 ::: 2335
#pragma line 167 "/usr/include/math.h" 3 4 ::: 2336
#pragma line 248 "/usr/include/math.h" 3 4 ::: 2403
#pragma line 268 "/usr/include/math.h" 3 4 ::: 2405
#pragma line 282 "/usr/include/math.h" 3 4 ::: 2407
#pragma line 304 "/usr/include/math.h" 3 4 ::: 2417
#pragma line 318 "/usr/include/math.h" 3 4 ::: 2419
#pragma line 346 "/usr/include/math.h" 3 4 ::: 2427
#pragma line 411 "/usr/include/math.h" 3 4 ::: 2481
#pragma line 428 "/usr/include/math.h" 3 4 ::: 2483
#pragma line 448 "/usr/include/math.h" 3 4 ::: 2487
#pragma line 470 "/usr/include/math.h" 3 4 ::: 2502
#pragma line 4 "awgn/solution1/awgn.c" 2 ::: 2558
