#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("input_axis_TDATA", 16, hls_in, 0, "axis", "in_data", 1),
	Port_Property("input_axis_TVALID", 1, hls_in, 0, "axis", "in_vld", 1),
	Port_Property("input_axis_TREADY", 1, hls_out, 0, "axis", "in_acc", 1),
	Port_Property("output_axis_TDATA", 16, hls_out, 1, "axis", "out_data", 1),
	Port_Property("output_axis_TVALID", 1, hls_out, 1, "axis", "out_vld", 1),
	Port_Property("output_axis_TREADY", 1, hls_in, 1, "axis", "out_acc", 1),
	Port_Property("s_axi_control_axil_AWVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_axil_AWREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_axil_AWADDR", 5, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_axil_WVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_axil_WREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_axil_WDATA", 32, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_axil_WSTRB", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_axil_ARVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_axil_ARREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_axil_ARADDR", 5, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_axil_RVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_axil_RREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_axil_RDATA", 32, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_axil_RRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_axil_BVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_axil_BREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_axil_BRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("interrupt", 1, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "awgn";
